name: latest-system
version: 0.2.0

library:
  dependencies:
    - base
    - directory
    - filepath
    - servant-server
    - text
  source-dirs:
    - src

executables:
  latest-system:
    source-dirs:
      - src-exe
    dependencies:
      - base
      - warp
      - latest-system
    main: Main
    other-modules: []
  latest-system-systemd:
    source-dirs:
      - src-exe
    dependencies:
      - base
      - warp
      - latest-system
      - wai-cli
    main: Systemd
    other-modules: []
